# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
schema.yml:
  no-ambiguous-paths:
    - '#/paths/~1api~1v2~1src101~1{deploy_hash}~1deploy'
    - '#/paths/~1api~1v2~1src101~1{deploy_hash}~1total'
    - '#/paths/~1api~1v2~1src101~1balance~1{address}'
    - '#/paths/~1api~1v2~1src101~1index~1{deploy_hash}~1{index}'
    - '#/paths/~1api~1v2~1stamps~1balance~1{address}'
    - '#/paths/~1api~1v2~1stamps~1block~1{block_index}'
    - '#/paths/~1api~1v2~1stamps~1ident~1{ident}'
  operation-2xx-response:
    - '#/paths/~1api~1v2~1error/get/responses'
