runner:
  denofmt:
    cmd: deno task check:fmt:debug 2>&1 | ./scripts/transform-deno-output.sh fmt
    format: rdjson
    level: warning
  denolint:
    cmd: deno task check:lint:debug 2>&1 | ./scripts/transform-deno-output.sh lint
    format: rdjson
    level: warning
github:
  reporter: github-pr-review
  filter_mode: file
  fail_on_error: false
