runner:
  denofmt:
    cmd: deno fmt --check .
    format: diff
    level: warning
  denolint:
    cmd: deno lint --json .
    format: rdjson
    level: warning
github:
  reporter: github-pr-review
  filter_mode: file
  fail_on_error: false
