// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_path_ from "./routes/[...path].ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about_index from "./routes/about/index.tsx";
import * as $api_path_ from "./routes/api/[...path].ts";
import * as $api_internal_bitcoinNotifications from "./routes/api/internal/bitcoinNotifications.ts";
import * as $api_internal_btcPrice from "./routes/api/internal/btcPrice.ts";
import * as $api_internal_carousel from "./routes/api/internal/carousel.ts";
import * as $api_internal_creatorName from "./routes/api/internal/creatorName.ts";
import * as $api_internal_csrfToken from "./routes/api/internal/csrfToken.ts";
import * as $api_internal_debug_headers from "./routes/api/internal/debug-headers.ts";
import * as $api_internal_fees from "./routes/api/internal/fees.ts";
import * as $api_internal_src20_trending from "./routes/api/internal/src20/trending.ts";
import * as $api_internal_src20Background from "./routes/api/internal/src20Background.ts";
import * as $api_v2_path_ from "./routes/api/v2/[...path].ts";
import * as $api_v2_balance_address_ from "./routes/api/v2/balance/[address].ts";
import * as $api_v2_balance_getStampsBalance from "./routes/api/v2/balance/getStampsBalance.ts";
import * as $api_v2_block_block_index_ from "./routes/api/v2/block/[block_index].ts";
import * as $api_v2_block_block_count_number_ from "./routes/api/v2/block/block_count/[...number].ts";
import * as $api_v2_block_related_block_index_ from "./routes/api/v2/block/related/[block_index].ts";
import * as $api_v2_collections_creator_creator_ from "./routes/api/v2/collections/creator/[creator].ts";
import * as $api_v2_collections_index from "./routes/api/v2/collections/index.ts";
import * as $api_v2_create_dispense from "./routes/api/v2/create/dispense.ts";
import * as $api_v2_create_send from "./routes/api/v2/create/send.ts";
import * as $api_v2_cursed_id_ from "./routes/api/v2/cursed/[id].ts";
import * as $api_v2_cursed_block from "./routes/api/v2/cursed/block.ts";
import * as $api_v2_cursed_block_block_index_ from "./routes/api/v2/cursed/block/[block_index].ts";
import * as $api_v2_cursed_index from "./routes/api/v2/cursed/index.ts";
import * as $api_v2_docs from "./routes/api/v2/docs.ts";
import * as $api_v2_error from "./routes/api/v2/error.ts";
import * as $api_v2_fairmint_compose from "./routes/api/v2/fairmint/compose.ts";
import * as $api_v2_fairmint_index from "./routes/api/v2/fairmint/index.ts";
import * as $api_v2_health from "./routes/api/v2/health.ts";
import * as $api_v2_olga_mint from "./routes/api/v2/olga/mint.ts";
import * as $api_v2_src101_deploy_hash_tokenid_ from "./routes/api/v2/src101/[deploy_hash]/[tokenid].ts";
import * as $api_v2_src101_deploy_hash_address_address_btc_ from "./routes/api/v2/src101/[deploy_hash]/address/[address_btc].ts";
import * as $api_v2_src101_deploy_hash_deploy from "./routes/api/v2/src101/[deploy_hash]/deploy.ts";
import * as $api_v2_src101_deploy_hash_index from "./routes/api/v2/src101/[deploy_hash]/index.ts";
import * as $api_v2_src101_deploy_hash_total from "./routes/api/v2/src101/[deploy_hash]/total.ts";
import * as $api_v2_src101_balance_address_ from "./routes/api/v2/src101/balance/[address].ts";
import * as $api_v2_src101_create from "./routes/api/v2/src101/create.ts";
import * as $api_v2_src101_index from "./routes/api/v2/src101/index.ts";
import * as $api_v2_src101_index_deploy_hash_index_ from "./routes/api/v2/src101/index/[deploy_hash]/[index].ts";
import * as $api_v2_src101_tx_tx_hash_ from "./routes/api/v2/src101/tx/[tx_hash].ts";
import * as $api_v2_src101_tx_index from "./routes/api/v2/src101/tx/index.ts";
import * as $api_v2_src20_op_ from "./routes/api/v2/src20/[...op].ts";
import * as $api_v2_src20_balance_address_ from "./routes/api/v2/src20/balance/[address].ts";
import * as $api_v2_src20_balance_address_tick_ from "./routes/api/v2/src20/balance/[address]/[tick].ts";
import * as $api_v2_src20_balance_snapshot_tick_ from "./routes/api/v2/src20/balance/snapshot/[tick].ts";
import * as $api_v2_src20_block_block_index_tick_ from "./routes/api/v2/src20/block/[block_index]/[tick].ts";
import * as $api_v2_src20_block_block_index_index from "./routes/api/v2/src20/block/[block_index]/index.ts";
import * as $api_v2_src20_create from "./routes/api/v2/src20/create.ts";
import * as $api_v2_src20_index from "./routes/api/v2/src20/index.ts";
import * as $api_v2_src20_multisig_operation_ from "./routes/api/v2/src20/multisig/[operation].ts";
import * as $api_v2_src20_search from "./routes/api/v2/src20/search.ts";
import * as $api_v2_src20_tick_tick_deploy from "./routes/api/v2/src20/tick/[tick]/deploy.ts";
import * as $api_v2_src20_tick_tick_index from "./routes/api/v2/src20/tick/[tick]/index.ts";
import * as $api_v2_src20_tick_tick_mintData from "./routes/api/v2/src20/tick/[tick]/mintData.ts";
import * as $api_v2_src20_tick_index from "./routes/api/v2/src20/tick/index.ts";
import * as $api_v2_src20_tx_tx_hash_ from "./routes/api/v2/src20/tx/[tx_hash].ts";
import * as $api_v2_stamp_stamp_preview from "./routes/api/v2/stamp/[stamp]/preview.ts";
import * as $api_v2_stamps_id_ from "./routes/api/v2/stamps/[id].ts";
import * as $api_v2_stamps_id_dispensers from "./routes/api/v2/stamps/[id]/dispensers.ts";
import * as $api_v2_stamps_id_dispenses from "./routes/api/v2/stamps/[id]/dispenses.ts";
import * as $api_v2_stamps_id_holders from "./routes/api/v2/stamps/[id]/holders.ts";
import * as $api_v2_stamps_id_sends from "./routes/api/v2/stamps/[id]/sends.ts";
import * as $api_v2_stamps_balance_address_ from "./routes/api/v2/stamps/balance/[address].tsx";
import * as $api_v2_stamps_block from "./routes/api/v2/stamps/block.ts";
import * as $api_v2_stamps_block_block_index_ from "./routes/api/v2/stamps/block/[block_index].ts";
import * as $api_v2_stamps_ident_ident_ from "./routes/api/v2/stamps/ident/[ident].ts";
import * as $api_v2_stamps_index from "./routes/api/v2/stamps/index.ts";
import * as $api_v2_stamps_recentSales from "./routes/api/v2/stamps/recentSales.ts";
import * as $api_v2_trx_complete_psbt from "./routes/api/v2/trx/complete_psbt.ts";
import * as $api_v2_trx_create_psbt from "./routes/api/v2/trx/create_psbt.ts";
import * as $api_v2_trx_stampattach from "./routes/api/v2/trx/stampattach.ts";
import * as $api_v2_trx_stampdetach from "./routes/api/v2/trx/stampdetach.ts";
import * as $api_v2_trx_utxoquery from "./routes/api/v2/trx/utxoquery.ts";
import * as $api_v2_utxo_ancestors_address_ from "./routes/api/v2/utxo/ancestors/[address].ts";
import * as $api_v2_version from "./routes/api/v2/version.ts";
import * as $block_block_index_ from "./routes/block/[block_index].tsx";
import * as $block_index from "./routes/block/index.tsx";
import * as $collection_id_ from "./routes/collection/[id].tsx";
import * as $collection_overview_ from "./routes/collection/[overview].tsx";
import * as $collection_index from "./routes/collection/index.tsx";
import * as $config from "./routes/config.ts";
import * as $content_imgpath_ from "./routes/content/[...imgpath].tsx";
import * as $dashboard_address_ from "./routes/dashboard/[address].tsx";
import * as $docs_index from "./routes/docs/index.tsx";
import * as $faq_index from "./routes/faq/index.tsx";
import * as $handlers_sharedBlockWithStampsHandler from "./routes/handlers/sharedBlockWithStampsHandler.ts";
import * as $handlers_sharedCollectionHandler from "./routes/handlers/sharedCollectionHandler.ts";
import * as $handlers_sharedContentHandler from "./routes/handlers/sharedContentHandler.ts";
import * as $handlers_sharedStampHandler from "./routes/handlers/sharedStampHandler.ts";
import * as $howto_deploytoken_index from "./routes/howto/deploytoken/index.tsx";
import * as $howto_index from "./routes/howto/index.tsx";
import * as $howto_leatherconnect_index from "./routes/howto/leatherconnect/index.tsx";
import * as $howto_leathercreate_index from "./routes/howto/leathercreate/index.tsx";
import * as $howto_minttoken_index from "./routes/howto/minttoken/index.tsx";
import * as $howto_registerbitname_index from "./routes/howto/registerbitname/index.tsx";
import * as $howto_stamp_index from "./routes/howto/stamp/index.tsx";
import * as $howto_template_index from "./routes/howto/template/index.tsx";
import * as $howto_transferbitname_index from "./routes/howto/transferbitname/index.tsx";
import * as $howto_transferstamp_index from "./routes/howto/transferstamp/index.tsx";
import * as $howto_transfertoken_index from "./routes/howto/transfertoken/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $media_index from "./routes/media/index.tsx";
import * as $presskit_index from "./routes/presskit/index.tsx";
import * as $s_id_ from "./routes/s/[...id].tsx";
import * as $src20_tick_ from "./routes/src20/[tick].tsx";
import * as $src20_index from "./routes/src20/index.tsx";
import * as $src20_minting from "./routes/src20/minting.tsx";
import * as $stamp_id_ from "./routes/stamp/[id].tsx";
import * as $stamp_art from "./routes/stamp/art.tsx";
import * as $stamp_index from "./routes/stamp/index.tsx";
import * as $stamp_posh from "./routes/stamp/posh.tsx";
import * as $termsofservice_index from "./routes/termsofservice/index.tsx";
import * as $test_design_system from "./routes/test/design-system.tsx";
import * as $test_test_image from "./routes/test/test-image.ts";
import * as $tool_fairmint_index from "./routes/tool/fairmint/index.tsx";
import * as $tool_src101_action_ from "./routes/tool/src101/[action].tsx";
import * as $tool_src20_action_ from "./routes/tool/src20/[action].tsx";
import * as $tool_src20_src20RedirectWIP from "./routes/tool/src20/src20RedirectWIP.tsx";
import * as $tool_stamp_action_ from "./routes/tool/stamp/[action].tsx";
import * as $tool_stamp_stamping from "./routes/tool/stamp/stamping.tsx";
import * as $tool_stamp_trade from "./routes/tool/stamp/trade.tsx";
import * as $upload_index from "./routes/upload/index.tsx";
import * as $wallet_address_ from "./routes/wallet/[address].tsx";
import * as $Toast_ToastComponent from "./islands/Toast/ToastComponent.tsx";
import * as $Toast_ToastProvider from "./islands/Toast/ToastProvider.tsx";
import * as $WIP_test_ReviewDogTest from "./islands/WIP/test/ReviewDogTest.tsx";
import * as $button_ConnectButton from "./islands/button/ConnectButton.tsx";
import * as $button_buttonActions from "./islands/button/buttonActions.tsx";
import * as $card_SRC20CardBase from "./islands/card/SRC20CardBase.tsx";
import * as $card_SRC20CardMinted from "./islands/card/SRC20CardMinted.tsx";
import * as $card_SRC20CardMinting from "./islands/card/SRC20CardMinting.tsx";
import * as $card_StampCard from "./islands/card/StampCard.tsx";
import * as $card_index from "./islands/card/index.ts";
import * as $card_styles from "./islands/card/styles.ts";
import * as $content_CollectionDetailContent from "./islands/content/CollectionDetailContent.tsx";
import * as $content_StampOverviewContent from "./islands/content/StampOverviewContent.tsx";
import * as $content_WalletDashboardContent from "./islands/content/WalletDashboardContent.tsx";
import * as $content_WalletDashboardDetails from "./islands/content/WalletDashboardDetails.tsx";
import * as $content_WalletDetails from "./islands/content/WalletDetails.tsx";
import * as $content_WalletDispenserDetails from "./islands/content/WalletDispenserDetails.tsx";
import * as $content_WalletProfileContent from "./islands/content/WalletProfileContent.tsx";
import * as $content_WalletProfileDetails from "./islands/content/WalletProfileDetails.tsx";
import * as $content_blockContent_BlockSelector from "./islands/content/blockContent/BlockSelector.tsx";
import * as $content_blockContent_BlockTransactions from "./islands/content/blockContent/BlockTransactions.tsx";
import * as $content_faqContent_AccordionBase from "./islands/content/faqContent/AccordionBase.tsx";
import * as $content_faqContent_FaqAccordion from "./islands/content/faqContent/FaqAccordion.tsx";
import * as $content_index from "./islands/content/index.ts";
import * as $content_stampDetailContent_StampImage from "./islands/content/stampDetailContent/StampImage.tsx";
import * as $content_stampDetailContent_StampInfo from "./islands/content/stampDetailContent/StampInfo.tsx";
import * as $content_stampDetailContent_StampTextContent from "./islands/content/stampDetailContent/StampTextContent.tsx";
import * as $datacontrol_Filter from "./islands/datacontrol/Filter.tsx";
import * as $datacontrol_Layout from "./islands/datacontrol/Layout.ts";
import * as $datacontrol_Pagination from "./islands/datacontrol/Pagination.tsx";
import * as $datacontrol_Search from "./islands/datacontrol/Search.tsx";
import * as $datacontrol_Setting from "./islands/datacontrol/Setting.tsx";
import * as $datacontrol_Sort from "./islands/datacontrol/Sort.tsx";
import * as $fee_ComplexFeeCalculator from "./islands/fee/ComplexFeeCalculator.tsx";
import * as $form_InputField from "./islands/form/InputField.tsx";
import * as $form_SRC20InputField from "./islands/form/SRC20InputField.tsx";
import * as $form_SelectDate from "./islands/form/SelectDate.tsx";
import * as $form_SelectField from "./islands/form/SelectField.tsx";
import * as $header_AboutHeader from "./islands/header/AboutHeader.tsx";
import * as $header_BlockHeader from "./islands/header/BlockHeader.tsx";
import * as $header_CollectionDetailHeader from "./islands/header/CollectionDetailHeader.tsx";
import * as $header_CollectionOverviewHeader from "./islands/header/CollectionOverviewHeader.tsx";
import * as $header_Header from "./islands/header/Header.tsx";
import * as $header_SRC20DetailHeader from "./islands/header/SRC20DetailHeader.tsx";
import * as $header_SRC20OverviewHeader from "./islands/header/SRC20OverviewHeader.tsx";
import * as $header_StampOverviewHeader from "./islands/header/StampOverviewHeader.tsx";
import * as $header_WalletDashboardHeader from "./islands/header/WalletDashboardHeader.tsx";
import * as $header_WalletProfileHeader from "./islands/header/WalletProfileHeader.tsx";
import * as $header_index from "./islands/header/index.ts";
import * as $layout_ChartWidget from "./islands/layout/ChartWidget.tsx";
import * as $layout_FontLoader from "./islands/layout/FontLoader.tsx";
import * as $layout_Footer from "./islands/layout/Footer.tsx";
import * as $layout_NavigatorProvider from "./islands/layout/NavigatorProvider.tsx";
import * as $loading_LoadingContent from "./islands/loading/LoadingContent.tsx";
import * as $loading_LoadingProvider from "./islands/loading/LoadingProvider.tsx";
import * as $modal_BuyStampModal from "./islands/modal/BuyStampModal.tsx";
import * as $modal_ConnectWalletModal from "./islands/modal/ConnectWalletModal.tsx";
import * as $modal_ConnectedModalWIP from "./islands/modal/ConnectedModalWIP.tsx";
import * as $modal_DetailSRC101Modal from "./islands/modal/DetailSRC101Modal.tsx";
import * as $modal_DonateStampModal from "./islands/modal/DonateStampModal.tsx";
import * as $modal_FilterSRC20Modal from "./islands/modal/FilterSRC20Modal.tsx";
import * as $modal_PreviewCodeModal from "./islands/modal/PreviewCodeModal.tsx";
import * as $modal_PreviewImageModal from "./islands/modal/PreviewImageModal.tsx";
import * as $modal_RecieveAddyModal from "./islands/modal/RecieveAddyModal.tsx";
import * as $modal_SendBTCModal from "./islands/modal/SendBTCModal.tsx";
import * as $modal_SendStampModalWIP from "./islands/modal/SendStampModalWIP.tsx";
import * as $modal_WalletProviderBase from "./islands/modal/WalletProviderBase.tsx";
import * as $modal_index from "./islands/modal/index.ts";
import * as $search_SRC20Search from "./islands/search/SRC20Search.tsx";
import * as $search_StampSearch from "./islands/search/StampSearch.tsx";
import * as $search_index from "./islands/search/index.ts";
import * as $search_styles from "./islands/search/styles.ts";
import * as $section_cta_ContactCta from "./islands/section/cta/ContactCta.tsx";
import * as $section_cta_DonateCta from "./islands/section/cta/DonateCta.tsx";
import * as $section_cta_GetStampingCta from "./islands/section/cta/GetStampingCta.tsx";
import * as $section_cta_RecursiveContactCta from "./islands/section/cta/RecursiveContactCta.tsx";
import * as $section_cta_StampPoshCta from "./islands/section/cta/StampPoshCta.tsx";
import * as $section_cta_StampchainContactCta from "./islands/section/cta/StampchainContactCta.tsx";
import * as $section_gallery_ArtistGallery from "./islands/section/gallery/ArtistGallery.tsx";
import * as $section_gallery_Carousel from "./islands/section/gallery/Carousel.tsx";
import * as $section_gallery_CollectionGallery from "./islands/section/gallery/CollectionGallery.tsx";
import * as $section_gallery_Partners from "./islands/section/gallery/Partners.tsx";
import * as $section_gallery_SRC20Deploys from "./islands/section/gallery/SRC20Deploys.tsx";
import * as $section_gallery_SRC20Gallery from "./islands/section/gallery/SRC20Gallery.tsx";
import * as $section_gallery_SRC20Mints from "./islands/section/gallery/SRC20Mints.tsx";
import * as $section_gallery_SRC20Transfers from "./islands/section/gallery/SRC20Transfers.tsx";
import * as $section_gallery_StampGallery from "./islands/section/gallery/StampGallery.tsx";
import * as $section_gallery_StampOverviewGallery from "./islands/section/gallery/StampOverviewGallery.tsx";
import * as $section_gallery_StampSales from "./islands/section/gallery/StampSales.tsx";
import * as $section_gallery_StampTransfers from "./islands/section/gallery/StampTransfers.tsx";
import * as $section_gallery_SwiperStyles from "./islands/section/gallery/SwiperStyles.tsx";
import * as $section_gallery_Team from "./islands/section/gallery/Team.tsx";
import * as $section_howto_HowToDeployToken from "./islands/section/howto/HowToDeployToken.tsx";
import * as $section_howto_HowToMintToken from "./islands/section/howto/HowToMintToken.tsx";
import * as $section_howto_HowToRegisterBitname from "./islands/section/howto/HowToRegisterBitname.tsx";
import * as $section_howto_HowToStamp from "./islands/section/howto/HowToStamp.tsx";
import * as $section_howto_HowToTransferBitname from "./islands/section/howto/HowToTransferBitname.tsx";
import * as $section_howto_HowToTransferStamp from "./islands/section/howto/HowToTransferStamp.tsx";
import * as $section_howto_HowToTransferToken from "./islands/section/howto/HowToTransferToken.tsx";
import * as $section_index from "./islands/section/index.ts";
import * as $table_DataTableBase from "./islands/table/DataTableBase.tsx";
import * as $table_HoldersPieChart from "./islands/table/HoldersPieChart.tsx";
import * as $table_HoldersTableBase from "./islands/table/HoldersTableBase.tsx";
import * as $table_UploadImageTable from "./islands/table/UploadImageTable.tsx";
import * as $table_index from "./islands/table/index.ts";
import * as $tool_StatusMessages from "./islands/tool/StatusMessages.tsx";
import * as $tool_fairmint_FairmintTool from "./islands/tool/fairmint/FairmintTool.tsx";
import * as $tool_index from "./islands/tool/index.ts";
import * as $tool_src101_RegisterTool from "./islands/tool/src101/RegisterTool.tsx";
import * as $tool_src20_DeployTool from "./islands/tool/src20/DeployTool.tsx";
import * as $tool_src20_MintTool from "./islands/tool/src20/MintTool.tsx";
import * as $tool_src20_TransferTool from "./islands/tool/src20/TransferTool.tsx";
import * as $tool_stamp_StampingTool from "./islands/tool/stamp/StampingTool.tsx";
import * as $tool_stamp_TradeTool from "./islands/tool/stamp/TradeTool.tsx";
import * as $tool_stamp_TransferTool from "./islands/tool/stamp/TransferTool.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[...path].ts": $_path_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about/index.tsx": $about_index,
    "./routes/api/[...path].ts": $api_path_,
    "./routes/api/internal/bitcoinNotifications.ts":
      $api_internal_bitcoinNotifications,
    "./routes/api/internal/btcPrice.ts": $api_internal_btcPrice,
    "./routes/api/internal/carousel.ts": $api_internal_carousel,
    "./routes/api/internal/creatorName.ts": $api_internal_creatorName,
    "./routes/api/internal/csrfToken.ts": $api_internal_csrfToken,
    "./routes/api/internal/debug-headers.ts": $api_internal_debug_headers,
    "./routes/api/internal/fees.ts": $api_internal_fees,
    "./routes/api/internal/src20/trending.ts": $api_internal_src20_trending,
    "./routes/api/internal/src20Background.ts": $api_internal_src20Background,
    "./routes/api/v2/[...path].ts": $api_v2_path_,
    "./routes/api/v2/balance/[address].ts": $api_v2_balance_address_,
    "./routes/api/v2/balance/getStampsBalance.ts":
      $api_v2_balance_getStampsBalance,
    "./routes/api/v2/block/[block_index].ts": $api_v2_block_block_index_,
    "./routes/api/v2/block/block_count/[...number].ts":
      $api_v2_block_block_count_number_,
    "./routes/api/v2/block/related/[block_index].ts":
      $api_v2_block_related_block_index_,
    "./routes/api/v2/collections/creator/[creator].ts":
      $api_v2_collections_creator_creator_,
    "./routes/api/v2/collections/index.ts": $api_v2_collections_index,
    "./routes/api/v2/create/dispense.ts": $api_v2_create_dispense,
    "./routes/api/v2/create/send.ts": $api_v2_create_send,
    "./routes/api/v2/cursed/[id].ts": $api_v2_cursed_id_,
    "./routes/api/v2/cursed/block.ts": $api_v2_cursed_block,
    "./routes/api/v2/cursed/block/[block_index].ts":
      $api_v2_cursed_block_block_index_,
    "./routes/api/v2/cursed/index.ts": $api_v2_cursed_index,
    "./routes/api/v2/docs.ts": $api_v2_docs,
    "./routes/api/v2/error.ts": $api_v2_error,
    "./routes/api/v2/fairmint/compose.ts": $api_v2_fairmint_compose,
    "./routes/api/v2/fairmint/index.ts": $api_v2_fairmint_index,
    "./routes/api/v2/health.ts": $api_v2_health,
    "./routes/api/v2/olga/mint.ts": $api_v2_olga_mint,
    "./routes/api/v2/src101/[deploy_hash]/[tokenid].ts":
      $api_v2_src101_deploy_hash_tokenid_,
    "./routes/api/v2/src101/[deploy_hash]/address/[address_btc].ts":
      $api_v2_src101_deploy_hash_address_address_btc_,
    "./routes/api/v2/src101/[deploy_hash]/deploy.ts":
      $api_v2_src101_deploy_hash_deploy,
    "./routes/api/v2/src101/[deploy_hash]/index.ts":
      $api_v2_src101_deploy_hash_index,
    "./routes/api/v2/src101/[deploy_hash]/total.ts":
      $api_v2_src101_deploy_hash_total,
    "./routes/api/v2/src101/balance/[address].ts":
      $api_v2_src101_balance_address_,
    "./routes/api/v2/src101/create.ts": $api_v2_src101_create,
    "./routes/api/v2/src101/index.ts": $api_v2_src101_index,
    "./routes/api/v2/src101/index/[deploy_hash]/[index].ts":
      $api_v2_src101_index_deploy_hash_index_,
    "./routes/api/v2/src101/tx/[tx_hash].ts": $api_v2_src101_tx_tx_hash_,
    "./routes/api/v2/src101/tx/index.ts": $api_v2_src101_tx_index,
    "./routes/api/v2/src20/[...op].ts": $api_v2_src20_op_,
    "./routes/api/v2/src20/balance/[address].ts":
      $api_v2_src20_balance_address_,
    "./routes/api/v2/src20/balance/[address]/[tick].ts":
      $api_v2_src20_balance_address_tick_,
    "./routes/api/v2/src20/balance/snapshot/[tick].ts":
      $api_v2_src20_balance_snapshot_tick_,
    "./routes/api/v2/src20/block/[block_index]/[tick].ts":
      $api_v2_src20_block_block_index_tick_,
    "./routes/api/v2/src20/block/[block_index]/index.ts":
      $api_v2_src20_block_block_index_index,
    "./routes/api/v2/src20/create.ts": $api_v2_src20_create,
    "./routes/api/v2/src20/index.ts": $api_v2_src20_index,
    "./routes/api/v2/src20/multisig/[operation].ts":
      $api_v2_src20_multisig_operation_,
    "./routes/api/v2/src20/search.ts": $api_v2_src20_search,
    "./routes/api/v2/src20/tick/[tick]/deploy.ts":
      $api_v2_src20_tick_tick_deploy,
    "./routes/api/v2/src20/tick/[tick]/index.ts": $api_v2_src20_tick_tick_index,
    "./routes/api/v2/src20/tick/[tick]/mintData.ts":
      $api_v2_src20_tick_tick_mintData,
    "./routes/api/v2/src20/tick/index.ts": $api_v2_src20_tick_index,
    "./routes/api/v2/src20/tx/[tx_hash].ts": $api_v2_src20_tx_tx_hash_,
    "./routes/api/v2/stamp/[stamp]/preview.ts": $api_v2_stamp_stamp_preview,
    "./routes/api/v2/stamps/[id].ts": $api_v2_stamps_id_,
    "./routes/api/v2/stamps/[id]/dispensers.ts": $api_v2_stamps_id_dispensers,
    "./routes/api/v2/stamps/[id]/dispenses.ts": $api_v2_stamps_id_dispenses,
    "./routes/api/v2/stamps/[id]/holders.ts": $api_v2_stamps_id_holders,
    "./routes/api/v2/stamps/[id]/sends.ts": $api_v2_stamps_id_sends,
    "./routes/api/v2/stamps/balance/[address].tsx":
      $api_v2_stamps_balance_address_,
    "./routes/api/v2/stamps/block.ts": $api_v2_stamps_block,
    "./routes/api/v2/stamps/block/[block_index].ts":
      $api_v2_stamps_block_block_index_,
    "./routes/api/v2/stamps/ident/[ident].ts": $api_v2_stamps_ident_ident_,
    "./routes/api/v2/stamps/index.ts": $api_v2_stamps_index,
    "./routes/api/v2/stamps/recentSales.ts": $api_v2_stamps_recentSales,
    "./routes/api/v2/trx/complete_psbt.ts": $api_v2_trx_complete_psbt,
    "./routes/api/v2/trx/create_psbt.ts": $api_v2_trx_create_psbt,
    "./routes/api/v2/trx/stampattach.ts": $api_v2_trx_stampattach,
    "./routes/api/v2/trx/stampdetach.ts": $api_v2_trx_stampdetach,
    "./routes/api/v2/trx/utxoquery.ts": $api_v2_trx_utxoquery,
    "./routes/api/v2/utxo/ancestors/[address].ts":
      $api_v2_utxo_ancestors_address_,
    "./routes/api/v2/version.ts": $api_v2_version,
    "./routes/block/[block_index].tsx": $block_block_index_,
    "./routes/block/index.tsx": $block_index,
    "./routes/collection/[id].tsx": $collection_id_,
    "./routes/collection/[overview].tsx": $collection_overview_,
    "./routes/collection/index.tsx": $collection_index,
    "./routes/config.ts": $config,
    "./routes/content/[...imgpath].tsx": $content_imgpath_,
    "./routes/dashboard/[address].tsx": $dashboard_address_,
    "./routes/docs/index.tsx": $docs_index,
    "./routes/faq/index.tsx": $faq_index,
    "./routes/handlers/sharedBlockWithStampsHandler.ts":
      $handlers_sharedBlockWithStampsHandler,
    "./routes/handlers/sharedCollectionHandler.ts":
      $handlers_sharedCollectionHandler,
    "./routes/handlers/sharedContentHandler.ts": $handlers_sharedContentHandler,
    "./routes/handlers/sharedStampHandler.ts": $handlers_sharedStampHandler,
    "./routes/howto/deploytoken/index.tsx": $howto_deploytoken_index,
    "./routes/howto/index.tsx": $howto_index,
    "./routes/howto/leatherconnect/index.tsx": $howto_leatherconnect_index,
    "./routes/howto/leathercreate/index.tsx": $howto_leathercreate_index,
    "./routes/howto/minttoken/index.tsx": $howto_minttoken_index,
    "./routes/howto/registerbitname/index.tsx": $howto_registerbitname_index,
    "./routes/howto/stamp/index.tsx": $howto_stamp_index,
    "./routes/howto/template/index.tsx": $howto_template_index,
    "./routes/howto/transferbitname/index.tsx": $howto_transferbitname_index,
    "./routes/howto/transferstamp/index.tsx": $howto_transferstamp_index,
    "./routes/howto/transfertoken/index.tsx": $howto_transfertoken_index,
    "./routes/index.tsx": $index,
    "./routes/media/index.tsx": $media_index,
    "./routes/presskit/index.tsx": $presskit_index,
    "./routes/s/[...id].tsx": $s_id_,
    "./routes/src20/[tick].tsx": $src20_tick_,
    "./routes/src20/index.tsx": $src20_index,
    "./routes/src20/minting.tsx": $src20_minting,
    "./routes/stamp/[id].tsx": $stamp_id_,
    "./routes/stamp/art.tsx": $stamp_art,
    "./routes/stamp/index.tsx": $stamp_index,
    "./routes/stamp/posh.tsx": $stamp_posh,
    "./routes/termsofservice/index.tsx": $termsofservice_index,
    "./routes/test/design-system.tsx": $test_design_system,
    "./routes/test/test-image.ts": $test_test_image,
    "./routes/tool/fairmint/index.tsx": $tool_fairmint_index,
    "./routes/tool/src101/[action].tsx": $tool_src101_action_,
    "./routes/tool/src20/[action].tsx": $tool_src20_action_,
    "./routes/tool/src20/src20RedirectWIP.tsx": $tool_src20_src20RedirectWIP,
    "./routes/tool/stamp/[action].tsx": $tool_stamp_action_,
    "./routes/tool/stamp/stamping.tsx": $tool_stamp_stamping,
    "./routes/tool/stamp/trade.tsx": $tool_stamp_trade,
    "./routes/upload/index.tsx": $upload_index,
    "./routes/wallet/[address].tsx": $wallet_address_,
  },
  islands: {
    "./islands/Toast/ToastComponent.tsx": $Toast_ToastComponent,
    "./islands/Toast/ToastProvider.tsx": $Toast_ToastProvider,
    "./islands/WIP/test/ReviewDogTest.tsx": $WIP_test_ReviewDogTest,
    "./islands/button/ConnectButton.tsx": $button_ConnectButton,
    "./islands/button/buttonActions.tsx": $button_buttonActions,
    "./islands/card/SRC20CardBase.tsx": $card_SRC20CardBase,
    "./islands/card/SRC20CardMinted.tsx": $card_SRC20CardMinted,
    "./islands/card/SRC20CardMinting.tsx": $card_SRC20CardMinting,
    "./islands/card/StampCard.tsx": $card_StampCard,
    "./islands/card/index.ts": $card_index,
    "./islands/card/styles.ts": $card_styles,
    "./islands/content/CollectionDetailContent.tsx":
      $content_CollectionDetailContent,
    "./islands/content/StampOverviewContent.tsx": $content_StampOverviewContent,
    "./islands/content/WalletDashboardContent.tsx":
      $content_WalletDashboardContent,
    "./islands/content/WalletDashboardDetails.tsx":
      $content_WalletDashboardDetails,
    "./islands/content/WalletDetails.tsx": $content_WalletDetails,
    "./islands/content/WalletDispenserDetails.tsx":
      $content_WalletDispenserDetails,
    "./islands/content/WalletProfileContent.tsx": $content_WalletProfileContent,
    "./islands/content/WalletProfileDetails.tsx": $content_WalletProfileDetails,
    "./islands/content/blockContent/BlockSelector.tsx":
      $content_blockContent_BlockSelector,
    "./islands/content/blockContent/BlockTransactions.tsx":
      $content_blockContent_BlockTransactions,
    "./islands/content/faqContent/AccordionBase.tsx":
      $content_faqContent_AccordionBase,
    "./islands/content/faqContent/FaqAccordion.tsx":
      $content_faqContent_FaqAccordion,
    "./islands/content/index.ts": $content_index,
    "./islands/content/stampDetailContent/StampImage.tsx":
      $content_stampDetailContent_StampImage,
    "./islands/content/stampDetailContent/StampInfo.tsx":
      $content_stampDetailContent_StampInfo,
    "./islands/content/stampDetailContent/StampTextContent.tsx":
      $content_stampDetailContent_StampTextContent,
    "./islands/datacontrol/Filter.tsx": $datacontrol_Filter,
    "./islands/datacontrol/Layout.ts": $datacontrol_Layout,
    "./islands/datacontrol/Pagination.tsx": $datacontrol_Pagination,
    "./islands/datacontrol/Search.tsx": $datacontrol_Search,
    "./islands/datacontrol/Setting.tsx": $datacontrol_Setting,
    "./islands/datacontrol/Sort.tsx": $datacontrol_Sort,
    "./islands/fee/ComplexFeeCalculator.tsx": $fee_ComplexFeeCalculator,
    "./islands/form/InputField.tsx": $form_InputField,
    "./islands/form/SRC20InputField.tsx": $form_SRC20InputField,
    "./islands/form/SelectDate.tsx": $form_SelectDate,
    "./islands/form/SelectField.tsx": $form_SelectField,
    "./islands/header/AboutHeader.tsx": $header_AboutHeader,
    "./islands/header/BlockHeader.tsx": $header_BlockHeader,
    "./islands/header/CollectionDetailHeader.tsx":
      $header_CollectionDetailHeader,
    "./islands/header/CollectionOverviewHeader.tsx":
      $header_CollectionOverviewHeader,
    "./islands/header/Header.tsx": $header_Header,
    "./islands/header/SRC20DetailHeader.tsx": $header_SRC20DetailHeader,
    "./islands/header/SRC20OverviewHeader.tsx": $header_SRC20OverviewHeader,
    "./islands/header/StampOverviewHeader.tsx": $header_StampOverviewHeader,
    "./islands/header/WalletDashboardHeader.tsx": $header_WalletDashboardHeader,
    "./islands/header/WalletProfileHeader.tsx": $header_WalletProfileHeader,
    "./islands/header/index.ts": $header_index,
    "./islands/layout/ChartWidget.tsx": $layout_ChartWidget,
    "./islands/layout/FontLoader.tsx": $layout_FontLoader,
    "./islands/layout/Footer.tsx": $layout_Footer,
    "./islands/layout/NavigatorProvider.tsx": $layout_NavigatorProvider,
    "./islands/loading/LoadingContent.tsx": $loading_LoadingContent,
    "./islands/loading/LoadingProvider.tsx": $loading_LoadingProvider,
    "./islands/modal/BuyStampModal.tsx": $modal_BuyStampModal,
    "./islands/modal/ConnectWalletModal.tsx": $modal_ConnectWalletModal,
    "./islands/modal/ConnectedModalWIP.tsx": $modal_ConnectedModalWIP,
    "./islands/modal/DetailSRC101Modal.tsx": $modal_DetailSRC101Modal,
    "./islands/modal/DonateStampModal.tsx": $modal_DonateStampModal,
    "./islands/modal/FilterSRC20Modal.tsx": $modal_FilterSRC20Modal,
    "./islands/modal/PreviewCodeModal.tsx": $modal_PreviewCodeModal,
    "./islands/modal/PreviewImageModal.tsx": $modal_PreviewImageModal,
    "./islands/modal/RecieveAddyModal.tsx": $modal_RecieveAddyModal,
    "./islands/modal/SendBTCModal.tsx": $modal_SendBTCModal,
    "./islands/modal/SendStampModalWIP.tsx": $modal_SendStampModalWIP,
    "./islands/modal/WalletProviderBase.tsx": $modal_WalletProviderBase,
    "./islands/modal/index.ts": $modal_index,
    "./islands/search/SRC20Search.tsx": $search_SRC20Search,
    "./islands/search/StampSearch.tsx": $search_StampSearch,
    "./islands/search/index.ts": $search_index,
    "./islands/search/styles.ts": $search_styles,
    "./islands/section/cta/ContactCta.tsx": $section_cta_ContactCta,
    "./islands/section/cta/DonateCta.tsx": $section_cta_DonateCta,
    "./islands/section/cta/GetStampingCta.tsx": $section_cta_GetStampingCta,
    "./islands/section/cta/RecursiveContactCta.tsx":
      $section_cta_RecursiveContactCta,
    "./islands/section/cta/StampPoshCta.tsx": $section_cta_StampPoshCta,
    "./islands/section/cta/StampchainContactCta.tsx":
      $section_cta_StampchainContactCta,
    "./islands/section/gallery/ArtistGallery.tsx":
      $section_gallery_ArtistGallery,
    "./islands/section/gallery/Carousel.tsx": $section_gallery_Carousel,
    "./islands/section/gallery/CollectionGallery.tsx":
      $section_gallery_CollectionGallery,
    "./islands/section/gallery/Partners.tsx": $section_gallery_Partners,
    "./islands/section/gallery/SRC20Deploys.tsx": $section_gallery_SRC20Deploys,
    "./islands/section/gallery/SRC20Gallery.tsx": $section_gallery_SRC20Gallery,
    "./islands/section/gallery/SRC20Mints.tsx": $section_gallery_SRC20Mints,
    "./islands/section/gallery/SRC20Transfers.tsx":
      $section_gallery_SRC20Transfers,
    "./islands/section/gallery/StampGallery.tsx": $section_gallery_StampGallery,
    "./islands/section/gallery/StampOverviewGallery.tsx":
      $section_gallery_StampOverviewGallery,
    "./islands/section/gallery/StampSales.tsx": $section_gallery_StampSales,
    "./islands/section/gallery/StampTransfers.tsx":
      $section_gallery_StampTransfers,
    "./islands/section/gallery/SwiperStyles.tsx": $section_gallery_SwiperStyles,
    "./islands/section/gallery/Team.tsx": $section_gallery_Team,
    "./islands/section/howto/HowToDeployToken.tsx":
      $section_howto_HowToDeployToken,
    "./islands/section/howto/HowToMintToken.tsx": $section_howto_HowToMintToken,
    "./islands/section/howto/HowToRegisterBitname.tsx":
      $section_howto_HowToRegisterBitname,
    "./islands/section/howto/HowToStamp.tsx": $section_howto_HowToStamp,
    "./islands/section/howto/HowToTransferBitname.tsx":
      $section_howto_HowToTransferBitname,
    "./islands/section/howto/HowToTransferStamp.tsx":
      $section_howto_HowToTransferStamp,
    "./islands/section/howto/HowToTransferToken.tsx":
      $section_howto_HowToTransferToken,
    "./islands/section/index.ts": $section_index,
    "./islands/table/DataTableBase.tsx": $table_DataTableBase,
    "./islands/table/HoldersPieChart.tsx": $table_HoldersPieChart,
    "./islands/table/HoldersTableBase.tsx": $table_HoldersTableBase,
    "./islands/table/UploadImageTable.tsx": $table_UploadImageTable,
    "./islands/table/index.ts": $table_index,
    "./islands/tool/StatusMessages.tsx": $tool_StatusMessages,
    "./islands/tool/fairmint/FairmintTool.tsx": $tool_fairmint_FairmintTool,
    "./islands/tool/index.ts": $tool_index,
    "./islands/tool/src101/RegisterTool.tsx": $tool_src101_RegisterTool,
    "./islands/tool/src20/DeployTool.tsx": $tool_src20_DeployTool,
    "./islands/tool/src20/MintTool.tsx": $tool_src20_MintTool,
    "./islands/tool/src20/TransferTool.tsx": $tool_src20_TransferTool,
    "./islands/tool/stamp/StampingTool.tsx": $tool_stamp_StampingTool,
    "./islands/tool/stamp/TradeTool.tsx": $tool_stamp_TradeTool,
    "./islands/tool/stamp/TransferTool.tsx": $tool_stamp_TransferTool,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
