openapi: 3.0.3
info:
  title: Stampchain - OpenAPI 3.0
  description: Stampchain API UI
  version: 2.0.0
externalDocs:
  description: Find out more about Stampchain
  url: 'http://stampchain.io'
servers:
  - url: 'https://stampchain.io'
    description:  Production server (uses live data)
  - url: "https://bitcoinstamps.xyz"
    description: Production server (uses live data)
  - url: 'http://localhost:8000'
  - url: 'https://dev.bitcoinstamps.xyz'

paths:
  /api/v2/stamps:
    get:
      summary: Get paginated stamps
      description: Retrieve a paginated list of stamps.
      parameters:
        - in: query
          name: limit
          example: 500
          schema:
            type: integer
          description: The maximum number of stamps to return per page. Defaults to 50.
        - in: query
          name: page
          example: 1
          schema:
            type: integer
          description: The page number to retrieve. Defaults to 1.
        - in: query
          name: sort
          example: desc
          schema:
            type: string
          description: The order of stamps.
      responses:
        '200':
          description: Successful response with paginated stamps.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedStampResponseBody'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

components:
  schemas:
    Pagination:
      type: object
      properties:
        page:
          type: number
        limit:
          type: number
        totalPages:
          type: number
        total:
          type: number
    SUBPROTOCOLS:
      type: string
      enum:
        - STAMP
        - SRC-20
        - SRC-721
    BlockRow:
      type: object
      properties:
        block_index:
          type: number
        block_hash:
          type: string
        block_time:
          oneOf:
            - type: number
            - type: string
              format: date-time
        previous_block_hash:
          type: string
        ledger_hash:
          type: string
        txlist_hash:
          type: string
        messages_hash:
          type: string
    SendsRow:
      type: object
      properties:
        from: 
          type: string
    DispenseRow:
      type: object
      properties:
        tx_hash:
          type: string
        block_index:
          type: integer
        cpid:
          type: string
        source:
          type: string
        destination:
          type: string
        dispenser_tx_hash:
          type: string
        dispense_quantity:
          type: integer
    DispenserRow:
      type: object
      properties:
        tx_hash:
          type: string
        block_index:
          type: number
        source:
          type: string
        cpid:
          type: string
        give_quantity:
          type: number
        give_remaining:
          type: number
        escrow_quantity:
          type: number
        satoshirate:
          type: number
        btcrate:
          type: number
        origin:
          type: string
        dispenses:
          type: array
          items:
            $ref: '#/components/schemas/DispenseRow'
      required:
        - tx_hash
        - block_index
        - source
        - cpid
        - give_quantity
        - give_remaining
        - escrow_quantity
        - satoshirate
        - btcrate
        - origin
    StampRow:
      type: object
      properties:
        stamp:
          oneOf:
            - type: number
        block_index:
          type: number
        cpid:
          type: string
        creator:
          type: string
        divisible:
          type: number
        keyburn:
          oneOf:
            - type: number
        locked:
          type: number
        stamp_base64:
          type: string
        stamp_mimetype:
          type: string
        stamp_url:
          type: string
        supply:
          oneOf:
            - type: number
            - type: string
          nullable: true
        tx_hash:
          type: string
        ident:
          $ref: "#/components/schemas/SUBPROTOCOLS"
        creator_name:
          oneOf:
            - type: string
        stamp_hash:
          type: string
        file_hash:
          type: string
    SendRow:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        cpid:
          oneOf:
            - type: string
            
        tick:
          oneOf:
            - type: string
            
        memo:
          type: string
        quantity:
          type: string
          format: int64
        tx_hash:
          type: string
        block_index:
          type: number
    HolderRow:
      type: object
      properties:
        address:
          type: string
        quantity:
          type: number
        divisible:
          type: number
    BlockInfo:
      type: object
      properties:
        block_info:
          $ref: "#/components/schemas/BlockRow"
    BtcInfo:
      type: object
      properties:
        address:
          type: string
        balance:
          type: number
        txCount:
          type: number
        unconfirmedBalance:
          type: number
        unconfirmedTxCount:
          type: number
    XCPParams:
      type: object
      properties:
        filters:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              op:
                type: string
              value:
                type: string
        address:
          type: string
        asset:
          type: string
    SRC20Balance:
      type: object
      properties:
        address:
          type: string
        p:
          type: string
        tick:
          type: string
        amt:
          type: number
        block_time:
          type: string
          format: date-time
        last_update:
          type: number
          description: "The block index of the last update to the balance"
        deploy_tx:
          type: string
          description: "the tx_hash of the deploy transaction"
        deploy_img:
          type: string
          description: "The image associated with the deploy token"
    Src20SnapShotDetail:
      type: object
      properties:
        tick: 
          type: string
        address:
          type: string
        balance:
          type: string
    Src20Detail:
      type: object
      properties:
        tx_hash:
          type: string
        block_index:
          type: number
        p:
          type: string
        op:
          type: string
        tick:
          type: string
        creator:
          type: string
        amt:
          oneOf:
            - type: number
        deci:
          type: number
        lim:
          type: string
        max:
          type: string
        destination:
          type: string
        block_time:
          type: string
        creator_name:
          oneOf:
            - type: string
        destination_name:
          type: string
    Src20SnapshotDetail:
      type: object
      properties:
        tick:
          type: string
        address:
          type: string
        balance:
          oneOf:
            - type: number
            - type: string
    StampBalance:
      type: object
      properties:
        cpid:
          type: string
        stamp:
          type: number
        stamp_base64:
          type: string
        stamp_url:
          type: string
        stamp_mimetype:
          type: string
        tx_hash:
          type: string
        divisible:
          type: number
        supply:
          oneOf:
            - type: number
            - type: string
        locked:
          oneOf:
            - type: number
            - type: boolean
        creator:
          type: string
        creator_name:
          oneOf:
            - type: string
        balance:
          oneOf:
            - type: number
            - type: string
    MintStatus:
      type: object
      properties:
        max_supply:
          type: string
        total_minted:
          type: string
        total_mints:
          type: number
        progress:
          type: string
        decimals:
          type: number
        limit:
          oneOf:
            - type: number
    SRC20TrxRequestParams:
      type: object
      properties:
        block_index:
          type: integer
          format: int32
          nullable: true
          description: The index of the block.
        tick:
          type: string
          nullable: true
          description: The tick value, possibly represented as an emoji.
        op:
          type: string
          nullable: true
          description: The operation type, if applicable.
        limit:
          type: integer
          format: int32
          default: 1000
          description: The maximum number of items to return.
        page:
          type: integer
          format: int32
          default: 1
          description: The page number for pagination.
        sort:
          type: string
          default: "ASC"
          description: The sorting order, ASC or DESC.
        tx_hash:
          type: string
          nullable: true
          description: The transaction hash, if filtering by transaction.
        address:
          type: string
          nullable: true
          description: The address involved in the transactions.
    PaginationQueryParams:
      type: object
      properties:
        limit:
          type: number
        page:
          type: number
    PaginatedRequest:
      type: object
      properties:
        query:
          $ref: "#/components/schemas/PaginationQueryParams"
    PaginatedStampResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            data:
              type: array
              items:
                $ref: "#/components/schemas/StampRow"
    PaginatedStampBalanceResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            data:
              type: array
              items:
                $ref: "#/components/schemas/StampBalance"
    PaginatedSrc20ResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            data:
              type: array
              items:
                $ref: "#/components/schemas/Src20Detail"
    PaginatedTickResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            mint_status:
              $ref: "#/components/schemas/MintStatus"
            data:
              type: array
              items:
                $ref: "#/components/schemas/Src20Detail"
    TickResponseBody:
      type: object
      properties:
        last_block:
          type: number
        mint_status:
          $ref: "#/components/schemas/MintStatus"
        data:
          $ref: "#/components/schemas/Src20Detail"
    Src20ResponseBody:
      type: object
      properties:
        last_block:
          type: number
        data:
          $ref: "#/components/schemas/Src20Detail"
    Src20SnapshotResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            snapshot_block:
              type: number
            data:
              $ref: "#/components/schemas/Src20SnapshotDetail"
    StampsAndSrc20:
      type: object
      properties:
        stamps:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
        src20:
          type: array
          items:
            $ref: "#/components/schemas/SRC20Balance"
    PaginatedSrc20BalanceResponseBody:
      type: object
      properties:
        last_block:
          type: number
        data:
          type: array
          items:
            $ref: "#/components/schemas/SRC20Balance"
    Src20BalanceResponseBody:
      type: object
      properties:
        last_block:
          type: number
        data:
          $ref: "#/components/schemas/SRC20Balance"
    PaginatedBalanceResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            btc:
              $ref: "#/components/schemas/BtcInfo"
            data:
              type: array
              items:
                $ref: "#/components/schemas/StampsAndSrc20"
    StampResponseBody:
      type: object
      properties:
        data:
          type: object
          properties:
            stamp:
              $ref: "#/components/schemas/StampRow"
        last_block:
          type: number
    StampsResponseBody:
      type: object
      properties:
        last_block:
          type: number
        data:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
    PaginatedIdResponseBody:
      type: object
      allOf:
        - $ref: '#/components/schemas/Pagination'
        - type: object
          properties:
            last_block:
              type: number
            ident:
              oneOf:
                - type: string
            data:
              type: array
              items:
                $ref: "#/components/schemas/StampRow"
    PaginatedDispenserResponseBody:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        totalPages:
          type: integer
        total:
          type: integer
        last_block:
          type: integer
        dispensers:
          type: array
          items:
            $ref: '#/components/schemas/DispenserRow'
    DispenserResponseBody:
      type: object
      properties:
        dispensers:
          type: array
          items:
            $ref: "#/components/schemas/DispenserRow"
        last_block:
          type: number
    ErrorResponseBody:
      type: object
      properties:
        error:
          type: string
    PaginatedResponseBody:
      oneOf:
        - $ref: "#/components/schemas/PaginatedStampResponseBody"
        - $ref: "#/components/schemas/ErrorResponseBody"
    BlockInfoResponseBody:
      type: object
      properties:
        block_info:
          $ref: "#/components/schemas/BlockRow"
        issuances:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
        last_block:
          type: number
    StampBlockResponseBody:
      type: object
      properties:
        block_info:
          $ref: "#/components/schemas/BlockRow"
        data:
          type: array
          items:
            $ref: "#/components/schemas/StampRow"
        last_block:
          type: number
    IdHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            id:
              oneOf:
                - type: string
                - type: number
    IdentHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            ident:
              type: string
    BlockHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            block_index:
              oneOf:
                - type: number
                - type: string
    AddressHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            address:
              type: string
    TickHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            tick:
              oneOf:
                - type: string
                - type: number
    BlockTickHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            block_index:
              oneOf:
                - type: number
                - type: string
            tick:
              oneOf:
                - type: string
                - type: number
    AddressTickHandlerContext:
      type: object
      properties:
        params:
          type: object
          properties:
            address:
              type: string
            tick:
              oneOf:
                - type: string
                - type: number
    TX:
      type: object
      properties:
        hex:
          type: string
    TXError:
      type: object
      properties:
        error:
          type: string
    SRC20InputData:
      type: object
      properties:
        op:
          type: string
        toAddress:
          type: string
        changeAddress:
          type: string
        tick:
          type: string
        feeRate:
          type: number
        max:
          oneOf:
            - type: number
            - type: string
              nullable: true
        lim:
          oneOf:
            - type: number
            - type: string
              nullable: true
        dec:
          type: number
          nullable: true
        amt:
          oneOf:
            - type: number
            - type: string
              nullable: true
    SRC20TransferInputData:
      type: object
      properties:
        op:
          type: string
        toAddress:
          type: string
        changeAddress:
          type: string
        fromAddress:
          oneOf:
            - type: string
              nullable: true
        tick:
          type: string
        feeRate:
          type: number
        max:
          oneOf:
            - type: number
            - type: string
              nullable: true
        lim:
          oneOf:
            - type: number
            - type: string
              nullable: true
        dec:
          type: number
          nullable: true
        amt:
          oneOf:
            - type: number
            - type: string
              nullable: true
    MintStampInputData:
      type: object
      properties:
        sourceWallet:
          type: string
        assetName:
          oneOf:
            - type: string
          nullable: true
        qty:
          type: number
        locked:
          type: boolean
        divisible:
          type: boolean
        filename:
          type: string
        file:
          type: string
        satsPerKB:
          type: number
        service_fee:
          oneOf:
            - type: number
          nullable: true
        service_fee_address:
          oneOf:
            - type: string
          nullable: true