/**
 * Error Constants for BTC Stamps Explorer
 * Runtime constants for error codes and mappings
 */

/**
 * Validation error codes
 */
export enum ValidationErrorCode {
  REQUIRED_FIELD = "VALIDATION_REQUIRED_FIELD",
  INVALID_FORMAT = "VALIDATION_INVALID_FORMAT",
  INVALID_TYPE = "VALIDATION_INVALID_TYPE",
  INVALID_LENGTH = "VALIDATION_INVALID_LENGTH",
  INVALID_RANGE = "VALIDATION_INVALID_RANGE",
  INVALID_PATTERN = "VALIDATION_INVALID_PATTERN",
  INVALID_EMAIL = "VALIDATION_INVALID_EMAIL",
  INVALID_URL = "VALIDATION_INVALID_URL",
  INVALID_DATE = "VALIDATION_INVALID_DATE",
  DUPLICATE_VALUE = "VALIDATION_DUPLICATE_VALUE",
  REFERENCE_NOT_FOUND = "VALIDATION_REFERENCE_NOT_FOUND",
}

/**
 * API error codes
 */
export enum APIErrorCode {
  BAD_REQUEST = "API_BAD_REQUEST",
  UNAUTHORIZED = "API_UNAUTHORIZED",
  FORBIDDEN = "API_FORBIDDEN",
  NOT_FOUND = "API_NOT_FOUND",
  METHOD_NOT_ALLOWED = "API_METHOD_NOT_ALLOWED",
  CONFLICT = "API_CONFLICT",
  GONE = "API_GONE",
  UNPROCESSABLE_ENTITY = "API_UNPROCESSABLE_ENTITY",
  TOO_MANY_REQUESTS = "API_TOO_MANY_REQUESTS",
  INTERNAL_ERROR = "API_INTERNAL_ERROR",
  BAD_GATEWAY = "API_BAD_GATEWAY",
  SERVICE_UNAVAILABLE = "API_SERVICE_UNAVAILABLE",
  GATEWAY_TIMEOUT = "API_GATEWAY_TIMEOUT",
}

/**
 * Bitcoin error codes
 */
export enum BitcoinErrorCode {
  INVALID_ADDRESS = "BITCOIN_INVALID_ADDRESS",
  INVALID_TRANSACTION = "BITCOIN_INVALID_TRANSACTION",
  INSUFFICIENT_FUNDS = "BITCOIN_INSUFFICIENT_FUNDS",
  TRANSACTION_TOO_LARGE = "BITCOIN_TRANSACTION_TOO_LARGE",
  FEE_TOO_LOW = "BITCOIN_FEE_TOO_LOW",
  FEE_TOO_HIGH = "BITCOIN_FEE_TOO_HIGH",
  UTXO_NOT_FOUND = "BITCOIN_UTXO_NOT_FOUND",
  SCRIPT_VALIDATION_ERROR = "BITCOIN_SCRIPT_VALIDATION_ERROR",
  NETWORK_ERROR = "BITCOIN_NETWORK_ERROR",
  NODE_UNAVAILABLE = "BITCOIN_NODE_UNAVAILABLE",
  MEMPOOL_FULL = "BITCOIN_MEMPOOL_FULL",
  DOUBLE_SPEND = "BITCOIN_DOUBLE_SPEND",
}

// SRC20ErrorCode moved to bottom of file to avoid duplicates

// StampErrorCode is defined in stampConstants.ts to avoid duplication

/**
 * Error severity levels
 */
export enum ErrorSeverity {
  LOW = "low",
  MEDIUM = "medium",
  HIGH = "high",
  CRITICAL = "critical",
}

/**
 * Collection validation error codes
 */
export enum CollectionValidationErrorCode {
  INVALID_ID = "INVALID_ID",
  INVALID_NAME = "INVALID_NAME",
  NAME_TOO_SHORT = "NAME_TOO_SHORT",
  NAME_TOO_LONG = "NAME_TOO_LONG",
  DESCRIPTION_TOO_LONG = "DESCRIPTION_TOO_LONG",
  INVALID_STAMP_COUNT = "INVALID_STAMP_COUNT",
  INVALID_STAMP_IDS = "INVALID_STAMP_IDS",
  DUPLICATE_STAMPS = "DUPLICATE_STAMPS",
  INVALID_CREATORS = "INVALID_CREATORS",
  TOO_MANY_CREATORS = "TOO_MANY_CREATORS",
  INVALID_IMAGE_URL = "INVALID_IMAGE_URL",
}

/**
 * SRC20 error codes for token-specific validation and processing errors
 */
export enum SRC20ErrorCode {
  INVALID_TICKER = "SRC20_INVALID_TICKER",
  TOKEN_NOT_FOUND = "SRC20_TOKEN_NOT_FOUND",
  TOKEN_ALREADY_EXISTS = "SRC20_TOKEN_ALREADY_EXISTS",
  INSUFFICIENT_BALANCE = "SRC20_INSUFFICIENT_BALANCE",
  INVALID_AMOUNT = "SRC20_INVALID_AMOUNT",
  MINT_LIMIT_EXCEEDED = "SRC20_MINT_LIMIT_EXCEEDED",
  TOKEN_FULLY_MINTED = "SRC20_TOKEN_FULLY_MINTED",
  INVALID_DECIMALS = "SRC20_INVALID_DECIMALS",
  DEPLOYMENT_FAILED = "SRC20_DEPLOYMENT_FAILED",
  TRANSFER_FAILED = "SRC20_TRANSFER_FAILED",
  MINT_FAILED = "SRC20_MINT_FAILED",
}

/**
 * Error type constants for categorizing different types of errors
 */
export enum ErrorType {
  NETWORK_ERROR = "network",
  API_ERROR = "api",
  DATA_ERROR = "data",
  VALIDATION_ERROR = "validation",
  TIMEOUT_ERROR = "timeout",
  AUTH_ERROR = "auth",
  UNKNOWN_ERROR = "unknown",
}

/**
 * HTTP status code to error code mapping
 */
export const HTTP_STATUS_TO_ERROR_CODE: Record<number, APIErrorCode> = {
  400: APIErrorCode.BAD_REQUEST,
  401: APIErrorCode.UNAUTHORIZED,
  403: APIErrorCode.FORBIDDEN,
  404: APIErrorCode.NOT_FOUND,
  405: APIErrorCode.METHOD_NOT_ALLOWED,
  409: APIErrorCode.CONFLICT,
  410: APIErrorCode.GONE,
  422: APIErrorCode.UNPROCESSABLE_ENTITY,
  429: APIErrorCode.TOO_MANY_REQUESTS,
  500: APIErrorCode.INTERNAL_ERROR,
  502: APIErrorCode.BAD_GATEWAY,
  503: APIErrorCode.SERVICE_UNAVAILABLE,
} as const;
