name: Devin PR Reviewer

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  issue_comment:
    types: [created, edited]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  devin-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Check if PR author is Devin
        id: check_author
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" == "devin-ai-integration" ]]; then
            echo "is_devin=true" >> $GITHUB_OUTPUT
          else
            echo "is_devin=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate PR Summary
        if: steps.check_author.outputs.is_devin == 'false'
        id: summary
        run: |
          # Get commit messages for context
          COMMIT_MESSAGES=$(git log --format=%s ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }})
          
          # Extract types of changes from conventional commits
          TYPES=$(echo "$COMMIT_MESSAGES" | grep -oE '^(feat|fix|refactor|style|test|docs|chore|perf|ci|build)' | sort | uniq)
          
          # Generate narrative summary
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          echo "## Pull Request Overview" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          
          # Analyze commit types to determine PR purpose
          if echo "$TYPES" | grep -q "feat"; then
            echo "### 🚀 New Features" >> $GITHUB_OUTPUT
            echo "$COMMIT_MESSAGES" | grep "^feat" | sed 's/^feat(\([^)]*\)): /- /' >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
          fi
          
          if echo "$TYPES" | grep -q "fix"; then
            echo "### 🔧 Bug Fixes" >> $GITHUB_OUTPUT
            echo "$COMMIT_MESSAGES" | grep "^fix" | sed 's/^fix(\([^)]*\)): /- /' >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
          fi
          
          if echo "$TYPES" | grep -q "refactor\|style\|perf"; then
            echo "### 🔄 Improvements" >> $GITHUB_OUTPUT
            echo "$COMMIT_MESSAGES" | grep -E "^(refactor|style|perf)" | sed -E 's/^(refactor|style|perf)(\([^)]*\))?: /- /' >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
          fi
          
          # Add impact analysis
          echo "### 📊 Impact Analysis" >> $GITHUB_OUTPUT
          echo "This PR primarily focuses on:" >> $GITHUB_OUTPUT
          if echo "$TYPES" | grep -q "feat"; then
            echo "- Adding new functionality to the system" >> $GITHUB_OUTPUT
          fi
          if echo "$TYPES" | grep -q "fix"; then
            echo "- Resolving existing issues and improving stability" >> $GITHUB_OUTPUT
          fi
          if echo "$TYPES" | grep -q "refactor\|style\|perf"; then
            echo "- Enhancing code quality and performance" >> $GITHUB_OUTPUT
          fi
          if echo "$TYPES" | grep -q "test"; then
            echo "- Improving test coverage and reliability" >> $GITHUB_OUTPUT
          fi
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Process PR Description
        if: steps.check_author.outputs.is_devin == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || '';
            const summary = process.env.SUMMARY;
            
            if (!prBody.trim()) {
              // If PR description is blank, post detailed comment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: summary
              });
            } else {
              // If PR has description, add supplementary insights
              const sections = summary.split('\n### ');
              const impactSection = sections.find(s => s.startsWith('📊 Impact Analysis'));
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `### 💡 Additional Context\n\n${impactSection || 'No additional impact analysis available.'}`
              });
            }
        env:
          SUMMARY: ${{ steps.summary.outputs.summary }}

  devin-pr-comment-response:
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Process Comment
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            // For now, just acknowledge the comment
            // In future versions, this could be expanded to parse and act on specific review comments
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Acknowledged review comment:\n> ${comment}\n\nDevin will process this feedback in a future update.`
            });
